module.exports =
  animation_timer_system: require './animation_timer_system'
  controller_system: require './controller_system'
  expire_system: require './expire_system'
  gravity_system: require './gravity_system'
  hud_system: require './hud_system'
  main_title_system: require './main_title_system'
  map_physics_system: require './map_physics_system'
  motion_system: require './motion_system'
  room_system: require './room_system'
  suit_animation_system: require './suit_animation_system'
  suit_control_system: require './suit_control_system'
  suit_sound_system: require './suit_sound_system'
  suit_velocity_system: require './suit_velocity_system'
  timer_system: require './timer_system'
  viewport_room_system: require './viewport_room_system'
  viewport_shuttle_system: require './viewport_shuttle_system'
  viewport_system: require './viewport_system'
