module.exports =
  animation_timer_system: require './animation_timer_system'
  controller_system: require './controller_system'
  expire_system: require './expire_system'
  hud_system: require './hud_system'
  main_title_system: require './main_title_system'
  room_system: require './room_system'
  timer_system: require './timer_system'
  viewport_room_system: require './viewport_room_system'
  viewport_system: require './viewport_system'
