module.exports =
  bullet_system: require './bullet_system'
  controller_system: require './controller_system'
  death_timer_system: require './death_timer_system'
  gravity_system: require './gravity_system'
  hit_box_visual_sync_system: require './hit_box_visual_sync_system'
  map_physics_system: require './map_physics_system'
  sound_sync_system: require './sound_sync_system'
  sound_system: require './sound_system'
  sprite_sync_system: require './sprite_sync_system'
  visual_timer_system: require './visual_timer_system'
