module.exports =
  animation_sync_system: require './animation_sync_system'
  ellipse_sync_system: require './ellipse_sync_system'
  hit_box_visual_sync_system: require './hit_box_visual_sync_system'
  label_sync_system: require './label_sync_system'
  map_sync_system: require './map_sync_system'
  rectangle_sync_system: require './rectangle_sync_system'
  room_sync_system: require './room_sync_system'
  sound_sync_system: require './sound_sync_system'
  viewport_sync_system: require './viewport_sync_system'
