module.exports =
  morph_ball_animation: require './morph_ball_animation'
  morph_ball_control: require './morph_ball_control'
  morph_ball_motion_oracle: require './morph_ball_motion_oracle'
  morph_ball_velocity: require './morph_ball_velocity'
  powerup_collection: require './powerup_collection'
  samus_action_velocity: require './samus_action_velocity'
  samus_hud: require './samus_hud'
  samus_morph: require './samus_morph'
  samus_motion: require './samus_motion'
  short_beam: require './short_beam'
  suit_animation: require './suit_animation'
  suit_control: require './suit_control'
  suit_motion_oracle: require './suit_motion_oracle'
  suit_sound: require './suit_sound'
  suit_velocity: require './suit_velocity'
