module.exports =
  morph_ball_control_system: require './morph_ball_control_system'
  morph_ball_motion_oracle: require './morph_ball_motion_oracle'
  morph_ball_velocity_system: require './morph_ball_velocity_system'
  motion_system: require './motion_system'
  powerup_collection_system: require './powerup_collection_system'
  samus_action_sounds: require './samus_action_sounds'
  samus_action_velocity: require './samus_action_velocity'
  samus_animation: require './samus_animation'
  samus_controller_action: require './samus_controller_action'
  samus_hud_system: require './samus_hud_system'
  samus_morph_system: require './samus_morph_system'
  samus_motion: require './samus_motion'
  short_beam_system: require './short_beam_system'
  suit_control_system: require './suit_control_system'
  suit_motion_oracle: require './suit_motion_oracle'
  suit_sound_system: require './suit_sound_system'
  suit_velocity_system: require './suit_velocity_system'
