MapData =
  Map1: [
    ['wall', { level: 3, length: 9 }]
    ['gap']
    ['wall', { level: 1, length: 30}]
    ['gap']
    ['wall', { level: 2, length: 18}]
    ['gap']
    ['stepWall', { level: 2, leftLength: 5, rightLength: 28 }]
    ['gap']
    ['wall', { level: 1, length: 10}]
    ['gap']
    ['wall', { level: 2, length: 6}]
    ['gap']
    ['wall', { level: 1, length: 8}]
    ['gap']
    ['wall', { level: 2, length: 6}]
    ['gap']
    ['wall', { level: 1, length: 8}]
    ['gap']
    ['wall', { level: 2, length: 7}]
    ['gap']
    ['wall', { level: 1, length: 16}]
    ['gap']
    ['wall', { level: 2, length: 6}]
    ['gap']
    ['wall', { level: 1, length: 22}]
    ['gap', 2]
    ['wall', { level: 2, length: 14}]
    ['gap', 2]
    ['wall', { level: 3, length: 8}]
    ['gap', 2]
    ['stepWall', { level: 3, leftLength: 5, rightLength: 12 }]
    ['gap', 3]
    ['wall', { level: 0, length: 8}]
    ['gap', 3]
    ['wall', { level: 1, length: 50}]
    ['gap', 20]
  ]

module.exports = MapData
